site_name: Data Structures & Algorithms
theme:
  name: material

repo_url: https://github.com/theevergreenstatecollege/upper-division-cs/dsa-23au

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
